test and code-fix for issue 232
mojolicious/json-validator pull request #233
Opened 2020-12-02 16:09 UTC by DrHyde

### Summary
Tightly-scoped `no warnings 'newline'` in the chunk of code that tries to figure out whether something is a file or a string of JSON, to avoid unnecessarily spitting out a warning when it's a JSON string that ends in a newline.

### Motivation
The warning is wrong and confusing.

### References
https://github.com/mojolicious/json-validator/issues/232

2020-12-02 17:42 UTC, abraxxa commented
Isn't a chomp the easier fix?

2020-12-03 22:22 UTC, DrHyde commented
Errm, yes, if I'd remembered it existed :-)

2020-12-04 03:15 UTC, jhthorsen requested changes
I'm not sure about this change. Can't we rather use a regexp to check if there's a newline?

2020-12-04 03:15 UTC, jhthorsen commented on t/newline-warnings.t
> +!);
I think adding "\n" is better. Right now it almost looks like a typo to me.

2020-12-04 03:15 UTC, jhthorsen commented on t/newline-warnings.t
> +use warnings;
Please use `use Mojo::Base -strict;` instead for consistency.

2020-12-04 03:15 UTC, jhthorsen commented on t/newline-warnings.t
> +JSON::Validator->new()->schema(q!{ "type": "object" }
Please remove parenthesis for consistency. (`new` vs `new()`)

2020-12-11 13:00 UTC, merged

2020-12-11 13:00 UTC, jhthorsen commented
Thanks!